"""Everything the ASHIKA Group site says, in Japanese and English. Edit text here; build.py turns it into pages."""

SERVICES = [
    {
        "key": "ashikanw",
        "name": "ASHIKA Network",
        "url": "https://www.ashikanw.com",
        "host": "ashikanw.com",
        "img": "ashikanw.webp",
        "ja": {
            "kind": "サーバーホスティング",
            "lead": "Discord Bot や Web アプリ、定期実行のスクリプトなど、動かし続けたいプログラムの置き場所を月 30 円から提供しています。",
            "points": [
                "大阪・北摂エリアのデータセンターで運用",
                "1 か月単位の契約で、長い縛りはなし",
                "Python・Node.js・Minecraft などをパネルから数クリックで",
            ],
        },
        "en": {
            "kind": "Server hosting",
            "lead": "A home for programs that must keep running, such as Discord bots, web apps and scheduled scripts, from 30 yen a month.",
            "points": [
                "Run in a data center in northern Osaka",
                "Month-to-month plans, no long contracts",
                "Python, Node.js, Minecraft and more in a few clicks",
            ],
        },
    },
    {
        "key": "storiamc",
        "name": "StoriaMC",
        "url": "https://storiamc.com",
        "host": "storiamc.com",
        "img": "storiamc.webp",
        "ja": {
            "kind": "ソフトウェア（オープンソース）",
            "lead": "大規模な Minecraft サーバーのためのサーバーソフトウェア「Storia」を開発しています。1 つのワールドを複数のサーバーで分担して動かせます。",
            "points": [
                "Storia Cluster：サーバー間を読み込み画面なしで移動",
                "RAM ワールド、Tick Guard、Linear 形式などの独自機能",
                "ソースコードを GitHub で公開",
            ],
        },
        "en": {
            "kind": "Software (open source)",
            "lead": "We build Storia, server software for large Minecraft servers. One world can run on several servers at once.",
            "points": [
                "Storia Cluster: move between servers without a loading screen",
                "RAM world, Tick Guard, the Linear region format and more",
                "Source code on GitHub",
            ],
        },
    },
    {
        "key": "sabalisu",
        "name": "SABALISU",
        "url": "https://minecrafts.jp",
        "host": "minecrafts.jp",
        "img": "sabalisu.webp",
        "ja": {
            "kind": "Minecraft サーバーリスト",
            "lead": "国内の Minecraft サーバーを探せるサーバーリストです。遊ぶ場所を探す人と、仲間を集めたいサーバーをつなぎます。",
            "points": [
                "プレイヤー数と PING を 5 分ごとに実測",
                "経済・サバイバル・PvP などのジャンルで探せる",
                "Microsoft アカウントでログインして投票",
            ],
        },
        "en": {
            "kind": "Minecraft server list",
            "lead": "A list of Minecraft servers in Japan, connecting players looking for a place to play with servers looking for players.",
            "points": [
                "Player counts and ping measured every 5 minutes",
                "Browse by genre: economy, survival, PvP and more",
                "Sign in with a Microsoft account to vote",
            ],
        },
    },
]

T = {
    "ja-jp": {
        "lang": "ja",
        "name": "日本語",
        "title": "ASHIKA Group",
        "desc": "ASHIKA Group は、サーバーホスティングの ASHIKA Network、Minecraft サーバーソフトウェアの StoriaMC、Minecraft サーバーリストの SABALISU を運営しています。",
        "nav": [("services/", "サービス"), ("vision/", "理念"), ("history/", "沿革"), ("supportprogram/", "支援プログラム"), ("join/", "お手伝い募集"), ("about/", "ASHIKA Group について")],
        "footer_links": [("about/", "ASHIKA Group について"), ("vision/", "理念"), ("history/", "沿革"), ("technology/", "技術・設備"), ("supportprogram/", "支援プログラム"), ("join/", "お手伝い募集"), ("brand/", "ブランド"), ("about/#contact", "お問い合わせ")],
        "skip": "本文へ移動",
        "menu": "メニュー",
        "theme": "表示の明るさを切り替える",
        "language": "言語",
        "hero_k": "ASHIKA Group",
        "hero_t": ["情報と世界を", "駆け巡る"],
        "hero_p": "ASHIKA Group は、サーバーとソフトウェアとコミュニティで、インターネットで何かをつくり、続けていく人を支えています。",
        "hero_cta": ("サービスを見る", "services/"),
        "hero_cta2": ("ASHIKA Group について", "about/"),
        "facts": [("3", "運営しているサービス"), ("30円", "サーバーは月額から"), ("OSS", "Storia はオープンソース"), ("大阪", "箕面市を拠点に運営")],
        "biz_k": "Services",
        "biz_t": "サービス",
        "biz_p": "置き場所をつくる、動かす仕組みをつくる、人と人をつなぐ。3 つのサービスを運営しています。",
        "visit": "サイトを見る",
        "more": "詳しく見る",
        "msg_k": "Message",
        "msg_t": "代表者挨拶",
        "msg_short": "動かし続けたいものを、動かし続けられる場所を。小さなチームでも、大きな仕組みに負けないサービスをつくります。",
        "msg_body": [
            "ASHIKA Group のウェブサイトをご覧いただき、ありがとうございます。",
            "「情報と世界を駆け巡る」。それが私たちの合言葉です。情報が自由に世界を行き交い、人と人がつながり続けるための仕組みを、私たちはつくっています。Discord の Bot、学校の課題でつくった Web アプリ、仲間と遊ぶための Minecraft サーバー。インターネットには、誰かが手間と時間をかけてつくり、動かし続けているものがたくさんあります。けれど、それを置いておく場所の費用や、規模が大きくなったときの仕組みの限界が、続けることを難しくしてしまう場面を、私自身も何度も見てきました。",
            "ASHIKA Network は、月 30 円から使えるサーバーで、その「置き場所」の壁を低くするために始めました。StoriaMC では、たくさんの人が集まる Minecraft サーバーでも快適に動き続けるソフトウェアを、ソースコードを公開しながら開発しています。SABALISU は、遊ぶ場所を探している人と、仲間を待っているサーバーをつなぐ場所です。",
            "どのサービスも、まだ小さなチームで運営しています。だからこそ、利用してくださる方の声に近いところで、一つひとつの改善を積み重ねていきます。これからも ASHIKA Group をよろしくお願いいたします。",
        ],
        "msg_sign": ("ASHIKA Group 代表", "赤枝 遼佳"),
        "co_k": "About",
        "co_t": "ASHIKA Group について",
        "profile_t": "組織概要",
        "profile": [
            ("名称", "ASHIKA Group（アシカグループ）"),
            ("代表", "代表　赤枝 遼佳（あかし はるか）"),
            ("所在地", "大阪府箕面市<br><small>詳しい住所は、ご請求をいただいた場合にお知らせします。</small>"),
            ("活動内容", "サーバーホスティング（ASHIKA Network）<br>ソフトウェア開発（StoriaMC）<br>Web サービス（SABALISU）"),
            ("お問い合わせ", "support[a]ashikanw.com<br><small>[a] を @ に置き換えてお送りください。</small>"),
        ],
        "org_t": "組織図",
        "org_p": "代表のもとで、3 つのサービスを運営しています。",
        "org_top": ("代表", "赤枝 遼佳"),
        "org_units": [("サーバーホスティング", "ASHIKA Network"), ("ソフトウェア開発", "StoriaMC"), ("Web サービス", "SABALISU")],
        "loc_t": "拠点",
        "loc": [("本拠地", "大阪府箕面市", "ASHIKA Group の運営拠点です。"), ("サーバー設備", "大阪府・北摂エリア", "ASHIKA Network をはじめ、各サービスのサーバーを運用しています。")],
        "contact_t": "お問い合わせ",
        "contact_p": "サービスについてのご質問は、各サービスのサポート窓口が早くお答えできます。それ以外のお問い合わせは、メールでお送りください。",
        "contact_mail": "メールで問い合わせる",
        "contact_rows": [("ASHIKA Network のご利用について", "https://link.ashikanw.com/discord", "Discord のサポート"), ("StoriaMC について", "https://github.com/AKSHRK-Dev/Storia/issues", "GitHub の Issue"), ("SABALISU について", "https://minecrafts.jp", "サイト内のお問い合わせ先")],
        "biz_page_p": "ASHIKA Group が運営しているサービスです。",
        "footer_tag": "情報と世界を駆け巡る",
        "footer_services": "サービス",
        "footer_group": "ASHIKA Group",
        "rights": "Copyright (c) {y} ASHIKA Group. All rights reserved.",
        "not_found": ("ページが見つかりません", "URL が間違っているか、ページが移動しました。", "トップページへ"),
    },
    "en-us": {
        "lang": "en",
        "name": "English",
        "title": "ASHIKA Group",
        "desc": "ASHIKA Group runs ASHIKA Network (server hosting), StoriaMC (Minecraft server software) and SABALISU (a Minecraft server list).",
        "nav": [("services/", "Services"), ("vision/", "Vision"), ("history/", "History"), ("supportprogram/", "Support program"), ("join/", "Join us"), ("about/", "About us")],
        "footer_links": [("about/", "About us"), ("vision/", "Vision"), ("history/", "History"), ("technology/", "Technology"), ("supportprogram/", "Support program"), ("join/", "Join us"), ("brand/", "Brand"), ("about/#contact", "Contact")],
        "skip": "Skip to content",
        "menu": "Menu",
        "theme": "Switch light and dark",
        "language": "Language",
        "hero_k": "ASHIKA Group",
        "hero_t": ["Across information,", "around the world."],
        "hero_p": "ASHIKA Group supports people who build things on the internet and keep them going, with servers, software and community.",
        "hero_cta": ("Our services", "services/"),
        "hero_cta2": ("About us", "about/"),
        "facts": [("3", "services we run"), ("¥30", "servers from, per month"), ("OSS", "Storia is open source"), ("Osaka", "based in Minoh")],
        "biz_k": "Services",
        "biz_t": "Our services",
        "biz_p": "A place to run things, the software to run them, and a way to find each other: three services.",
        "visit": "Visit site",
        "more": "Learn more",
        "msg_k": "Message",
        "msg_t": "A message from our representative",
        "msg_short": "A place where the things you want to keep running can keep running. A small team building services that hold their own against big systems.",
        "msg_body": [
            "Thank you for visiting ASHIKA Group.",
            "Across information, around the world: that is our motto. We build what lets information travel freely and keeps people connected. A Discord bot, a web app from a school project, a Minecraft server for friends: the internet is full of things that someone built with their own time and keeps running. Yet I have seen many times how the cost of a place to run them, or the limits of the setup once they grow, makes it hard to keep going.",
            "ASHIKA Network started to lower that first barrier, with servers from 30 yen a month. With StoriaMC we build open-source software that keeps busy Minecraft servers running smoothly. SABALISU is where players looking for a place to play meet the servers waiting for them.",
            "All of our services are still run by a small team. That keeps us close to the people who use them, and we will keep improving them one step at a time. Thank you for your continued support of ASHIKA Group.",
        ],
        "msg_sign": ("Representative, ASHIKA Group", "Haruka Akashi"),
        "co_k": "About",
        "co_t": "About us",
        "profile_t": "Overview",
        "profile": [
            ("Name", "ASHIKA Group"),
            ("Representative", "Haruka Akashi"),
            ("Location", "Minoh, Osaka, Japan<br><small>The full address is available on request.</small>"),
            ("Activities", "Server hosting (ASHIKA Network)<br>Software development (StoriaMC)<br>Web services (SABALISU)"),
            ("Contact", "support[a]ashikanw.com<br><small>Replace [a] with @.</small>"),
        ],
        "org_t": "Organization",
        "org_p": "Three services under one representative.",
        "org_top": ("Representative", "Haruka Akashi"),
        "org_units": [("Server hosting", "ASHIKA Network"), ("Software", "StoriaMC"), ("Web services", "SABALISU")],
        "loc_t": "Locations",
        "loc": [("Headquarters", "Minoh, Osaka", "Where ASHIKA Group is run from."), ("Servers", "Northern Osaka", "Where ASHIKA Network and our other services run.")],
        "contact_t": "Contact",
        "contact_p": "For questions about a service, its own support is the fastest. For anything else, please send us an email.",
        "contact_mail": "Send an email",
        "contact_rows": [("Using ASHIKA Network", "https://link.ashikanw.com/discord", "Support on Discord"), ("About StoriaMC", "https://github.com/AKSHRK-Dev/Storia/issues", "Issues on GitHub"), ("About SABALISU", "https://minecrafts.jp", "Contact on the site")],
        "biz_page_p": "The services ASHIKA Group runs.",
        "footer_tag": "Across information, around the world.",
        "footer_services": "Services",
        "footer_group": "ASHIKA Group",
        "rights": "Copyright (c) {y} ASHIKA Group. All rights reserved.",
        "not_found": ("Page not found", "The address may be wrong, or the page has moved.", "Back to the top page"),
    },
}


# ---------------------------------------------------------------------------------------------
# History: only dates that can be checked (legal pages, GitHub releases, site launches).
# (date, category, ja title, ja text, en title, en text, future?)
# ---------------------------------------------------------------------------------------------
HISTORY = [
    ("2026-07-21", "network",
     "利用規約などを制定", "ASHIKA Network の利用規約、利用方針（AUP）、プライバシーポリシーを定めました。",
     "Terms of service", "ASHIKA Network's terms of service, acceptable use policy and privacy policy took effect.", False),
    ("2026-09-09", "network",
     "チャージ残高の表示を制定", "お客様パネルのチャージ残高について、資金決済法に基づく表示を定めました。",
     "Prepaid balance notice", "The notice under the Payment Services Act for the prepaid balance in the customer panel.", False),
    ("2026-09-26", "storia",
     "Storia を公開", "大規模な Minecraft サーバーのためのサーバーソフトウェア「Storia」の最初のリリース（26.2）を公開し、公式サイト storiamc.com を開設しました。",
     "Storia released", "The first release of Storia (26.2), server software for large Minecraft servers, and its website storiamc.com.", False),
    ("2026-09-27", "storia",
     "Storia Cluster を搭載", "1 つのワールドを複数のサーバーで分担して動かす Storia Cluster を、Storia 26.2-2 で搭載しました。",
     "Storia Cluster", "Storia 26.2-2 brought Storia Cluster: one world, run by several servers at once.", False),
    ("2026-09-28", "storia",
     "プラグイン API を公開", "Cluster の全ワーカーでデータを共有できるプラグイン API を、Storia 26.2-4 で公開しました。",
     "Plugin API", "Storia 26.2-4 added a plugin API that shares data across every worker of a cluster.", False),
    ("2026-10-03", "storia",
     "Linear 形式と予備の Relay", "Storia 26.2-10 で、ディスクの使用量をおよそ半分にする Linear 形式と、壊れても引き継げる予備の Relay に対応しました。",
     "Linear format and a standby relay", "Storia 26.2-10: the Linear region format, about half the disk space, and a standby relay that takes over if the active one is lost.", False),
    ("2026-10-03", "group",
     "ASHIKA Group のサイトを公開", "3 つのサービスをまとめる、ASHIKA Group のウェブサイトを公開しました。",
     "ASHIKA Group website", "The website of ASHIKA Group, home of our three services, went live.", False),
    ("2026-10-13", "network",
     "VPS の受け付けを開始", "専有の IPv4 アドレスとルート権限が付いた VPS の受け付けを始めます。",
     "VPS orders open", "Orders open for VPS plans with a dedicated IPv4 address and root access.", True),
]

REPOS = [
    ("Storia", "AKSHRK-Dev/Storia", "Storia 本体（Folia をもとにしたサーバー）", "Storia itself (a Folia-based server)"),
    ("StoriaProxy", "AKSHRK-Dev/StoriaProxy", "Velocity をもとにしたプロキシ", "A proxy based on Velocity"),
    ("StoriaSite", "AKSHRK-Dev/StoriaSite", "storiamc.com のソース", "Source of storiamc.com"),
    ("ashika-network-site", "AKSHRK-Dev/ashika-network-site", "ashikanw.com のソース", "Source of ashikanw.com"),
    ("ashika-group-site", "AKSHRK-Dev/ashika-group-site", "このサイトのソース", "Source of this website"),
]

COLORS = [("Navy", "#14497e"), ("Blue", "#1b60a6"), ("Ink", "#0e1a2b"), ("Mist", "#f4f7fb"), ("Sky", "#7fb2ea")]

T["ja-jp"].update({
    "ticker": "情報と世界を駆け巡る",
    "cat": {"network": "ASHIKA Network", "storia": "StoriaMC", "group": "ASHIKA Group"},
    "seal_hint": "アシカをつついてみてください",
    "seal_count": "{n} 回つつきました",
    "konami": "アシカがいっぱい！",
    "copied": "コピーしました",
    "future": "予定",
    "date_fmt": "{y}年{m}月{d}日",
    "month_fmt": "{m}月{d}日",
    # vision
    "vision_k": "Vision",
    "vision_t": "理念",
    "vision_p": "「情報と世界を駆け巡る」にこめたことと、ASHIKA Group が大切にしていることです。",
    "words_t": "この言葉にこめたこと",
    "words": [
        ("情報", "Information", "プログラム、言葉、作品、遊び。インターネットを流れるあらゆるものを、私たちは「情報」と呼んでいます。"),
        ("世界", "World", "画面の向こうにいる人たち、ゲームの中に広がる世界、そして私たちが暮らすこの世界。情報は、いつも誰かの世界とつながっています。"),
        ("駆け巡る", "Racing across", "止まらずに、遠くまで、速く。誰かがつくったものが、それを必要とする人のところへ届き続けること。それを支えるのが私たちの仕事です。"),
    ],
    "values_t": "大切にしていること",
    "values": [
        ("止めない", "動き続けることを、いちばんに考えます。Storia の予備の Relay のように、どこかが壊れても止まらない仕組みを選びます。"),
        ("手の届く価格で", "はじめの一歩をためらわないように。ASHIKA Network のサーバーは、月 30 円から使えます。"),
        ("ひらいてつくる", "Storia も、このサイトも、ソースコードを公開しています。誰でも中身を確かめ、手を加えられます。"),
        ("声の近くで", "小さなチームだからこそ、使ってくださる方の声を、すぐに形にします。"),
    ],
    "map_t": "3 つのサービスと理念",
    "map": {
        "ashikanw": ("情報の置き場所", "Bot や Web アプリが、休まず動き続ける場所をつくります。"),
        "storiamc": ("世界を動かす仕組み", "たくさんの人が集まる Minecraft の世界を、止めずに動かします。"),
        "sabalisu": ("世界への入り口", "遊ぶ場所を探す人と、仲間を待つサーバーをつなぎます。"),
    },
    # history
    "hist_k": "History",
    "hist_t": "沿革",
    "hist_p": "ASHIKA Group のこれまでと、これからの予定です。",
    "hist_home_t": "最近のできごと",
    "hist_all": "沿革をすべて見る",
    # technology
    "tech_k": "Technology",
    "tech_t": "技術・設備",
    "tech_p": "サービスを支えている設備と技術です。",
    "tech_stats": [("5", "", "公開しているリポジトリ"), ("5", "分", "ごとにサーバーを計測"), ("1/2", "", "Linear 形式のディスク使用量"), ("30", "円", "サーバーは月額から")],
    "tech": [
        ("ashikanw", "サーバー設備", [
            ("設置場所", "大阪府・北摂エリアのデータセンター"),
            ("動かせるもの", "Python、Node.js、Minecraft など。パネルから数クリックで用意できます。"),
            ("VPS（10 月 13 日から）", "専有の IPv4 アドレスとルート権限付き。最大 64 GB メモリ、10 コア、500 GB SSD。"),
        ]),
        ("storiamc", "サーバーソフトウェア", [
            ("土台", "Paper から派生したマルチスレッドのサーバー Folia をもとに開発。Java 25、Minecraft 26.2 に対応。"),
            ("Storia Cluster", "1 つのワールドを複数のサーバーで分担。サーバー間の通信は、すべて暗号化（AES-GCM）しています。"),
            ("止まらない仕組み", "予備の Storia Relay が本番の内容をその場で写し続け、壊れても引き継げます。"),
            ("保存", "Linear 形式（Zstandard 圧縮）で、ワールドのディスク使用量をおよそ半分に。"),
        ]),
        ("sabalisu", "Web サービス", [
            ("計測", "登録されたサーバーのプレイヤー数と PING を、5 分ごとに実測しています。"),
            ("ログイン", "Microsoft アカウントでログインして投票できます。"),
        ]),
    ],
    "web_t": "ウェブサイト",
    "web": [
        ("配信", "Cloudflare を通して配信し、通信はすべて HTTPS です。"),
        ("このサイト", "Python で作る静的なサイトです。アクセス解析や、追跡のための Cookie は使っていません。"),
    ],
    "oss_t": "オープンソース",
    "oss_p": "次のリポジトリを GitHub で公開しています。",
    # brand
    "brand_k": "Brand",
    "brand_t": "ブランド",
    "brand_p": "ASHIKA Group のマークと色の使い方です。ASHIKA Group やサービスを紹介するときにお使いください。",
    "mark_t": "マーク",
    "mark_p": "ボールを鼻にのせたアシカのマークです。このサイトのトップページのアシカは、ボールの代わりに地球をのせています。",
    "rules_t": "使うときのお願い",
    "rules": [
        ("余白をとる", "マークのまわりに、ボールの直径くらいの余白を空けてください。"),
        ("形を変えない", "伸ばしたり、傾けたり、影や縁取りを付けたりしないでください。"),
        ("色を変えない", "マークの色はネイビーです。暗い背景では、明るくしたものを使います。"),
    ],
    "colors_t": "色",
    "colors_p": "色をクリックすると、カラーコードをコピーできます。",
    "color_use": {"Navy": "メインの色", "Blue": "リンク・アクセント", "Ink": "文字", "Mist": "背景", "Sky": "暗い背景でのメインの色"},
    "type_t": "文字",
    "type_p": "欧文は Inter、和文は Noto Sans JP を使っています。",
    "dl_t": "ダウンロード",
    "dl": [("mark.png", "マーク（PNG・512 × 339）"), ("og.png", "SNS 用の画像（PNG・1200 × 630）")],
    # 404 game
    "game_t": "ボールを落とさないで！",
    "game_p": "ボールをクリック（タップ）して打ち上げてください。何回続くかな？",
    "game_score": "回",
    "game_best": "ベスト",
    "game_start": "スタート",
    "game_again": "もう一度",
})

T["en-us"].update({
    "ticker": "Across information, around the world",
    "cat": {"network": "ASHIKA Network", "storia": "StoriaMC", "group": "ASHIKA Group"},
    "seal_hint": "Give the seal a poke",
    "seal_count": "Poked {n} times",
    "konami": "Seals everywhere!",
    "copied": "Copied",
    "future": "Planned",
    "date_fmt": "{mon} {d}, {y}",
    "month_fmt": "{mon} {d}",
    "vision_k": "Vision",
    "vision_t": "Vision",
    "vision_p": "What we mean by “across information, around the world,” and what matters to ASHIKA Group.",
    "words_t": "What the words mean",
    "words": [
        ("Information", "情報", "Programs, words, creations, play. Everything that flows through the internet is what we call information."),
        ("World", "世界", "The people on the other side of the screen, the worlds inside games, and the world we live in. Information always connects to someone's world."),
        ("Around", "駆け巡る", "Without stopping, far and fast: what someone made keeps reaching the people who need it. Supporting that is our job."),
    ],
    "values_t": "What matters to us",
    "values": [
        ("Keep running", "Staying up comes first. Like Storia's standby relay, we choose designs that keep going when something breaks."),
        ("Within reach", "The first step should be easy. ASHIKA Network servers start at 30 yen a month."),
        ("Built in the open", "Storia and this website are open source. Anyone can read the code and improve it."),
        ("Close to you", "As a small team, we can turn what users tell us into improvements quickly."),
    ],
    "map_t": "Three services, one vision",
    "map": {
        "ashikanw": ("A home for information", "A place where bots and web apps keep running."),
        "storiamc": ("What keeps worlds running", "Busy Minecraft worlds, kept running without a stop."),
        "sabalisu": ("A door to new worlds", "Connecting players looking for a place to play with servers waiting for them."),
    },
    "hist_k": "History",
    "hist_t": "History",
    "hist_p": "Where ASHIKA Group has been, and what comes next.",
    "hist_home_t": "Recent milestones",
    "hist_all": "See the full history",
    "tech_k": "Technology",
    "tech_t": "Technology",
    "tech_p": "The facilities and technology behind our services.",
    "tech_stats": [("5", "", "open-source repositories"), ("5", " min", "between server checks"), ("1/2", "", "disk space with Linear"), ("30", " yen", "servers from, per month")],
    "tech": [
        ("ashikanw", "Server facilities", [
            ("Location", "A data center in northern Osaka"),
            ("What runs", "Python, Node.js, Minecraft and more, set up in a few clicks in the panel."),
            ("VPS (from October 13)", "A dedicated IPv4 address and root access. Up to 64 GB of memory, 10 cores and a 500 GB SSD."),
        ]),
        ("storiamc", "Server software", [
            ("Foundation", "Built on Folia, the multithreaded fork of Paper. Java 25, Minecraft 26.2."),
            ("Storia Cluster", "One world shared by several servers. All traffic between them is encrypted (AES-GCM)."),
            ("No single point of failure", "A standby Storia Relay keeps a live copy and takes over if the active one is lost."),
            ("Storage", "The Linear region format (Zstandard) uses about half the disk space."),
        ]),
        ("sabalisu", "Web service", [
            ("Measured", "Player counts and ping of listed servers, measured every 5 minutes."),
            ("Sign-in", "Sign in with a Microsoft account to vote."),
        ]),
    ],
    "web_t": "Websites",
    "web": [
        ("Delivery", "Served through Cloudflare, HTTPS only."),
        ("This website", "A static site built with Python. No analytics and no tracking cookies."),
    ],
    "oss_t": "Open source",
    "oss_p": "These repositories are public on GitHub.",
    "brand_k": "Brand",
    "brand_t": "Brand",
    "brand_p": "How to use the ASHIKA Group mark and colors when you write about ASHIKA Group or our services.",
    "mark_t": "The mark",
    "mark_p": "A seal balancing a ball on its nose. On this website's home page, the seal balances the globe instead.",
    "rules_t": "Please",
    "rules": [
        ("Give it room", "Leave space around the mark, about the size of the ball."),
        ("Keep its shape", "Do not stretch, tilt, or add shadows or outlines."),
        ("Keep its color", "The mark is navy. On dark backgrounds, use a lighter version."),
    ],
    "colors_t": "Colors",
    "colors_p": "Click a color to copy its code.",
    "color_use": {"Navy": "Main color", "Blue": "Links and accents", "Ink": "Text", "Mist": "Background", "Sky": "Main color on dark backgrounds"},
    "type_t": "Type",
    "type_p": "Inter for Latin text and Noto Sans JP for Japanese.",
    "dl_t": "Downloads",
    "dl": [("mark.png", "The mark (PNG, 512 × 339)"), ("og.png", "Social image (PNG, 1200 × 630)")],
    "game_t": "Don't drop the ball!",
    "game_p": "Click (or tap) the ball to keep it in the air. How long can you last?",
    "game_score": "hits",
    "game_best": "Best",
    "game_start": "Start",
    "game_again": "Play again",
})


# ---------------------------------------------------------------------------------------------
# Join us: helpers wanted, and the member terms (/join/terms/)
# ---------------------------------------------------------------------------------------------
JOIN_SERVERS = 5
TERMS_DATE = "2026-10-04"

T["ja-jp"].update({
    "join_k": "Join us",
    "join_t": "お手伝い募集",
    "join_p": "ASHIKA Group は、小さなチームで運営しています。一緒にサービスを支えてくれる人を募集しています。",
    "join_open": "募集中",
    "join_home_t": "一緒に、つくりませんか。",
    "join_home_p": "技術者とお客様対応のお手伝いを募集しています。参加中は ASHIKA Network のサーバーを最大 5 台まで無料で使えます。",
    "roles_t": "募集している役割",
    "roles": [
        ("engineer", "技術者", "Engineer", "サービスを動かす仕組みを、一緒につくって守る役割です。", [
            "ASHIKA Network のサーバーやお客様パネルの保守・改善",
            "Storia（Minecraft サーバーソフトウェア）の開発",
            "各サービスのウェブサイトの改善",
            "障害が起きたときの調査と復旧の手伝い",
        ], "Linux・Docker・TypeScript・Python・Java のどれかに触れたことがある方。小さくても、自分で作って動かしたものがある方は大歓迎です。"),
        ("support", "お客様対応", "Support", "使ってくださる方のいちばん近くで、困りごとを解決する役割です。", [
            "Discord のチケットやお問い合わせへの返信",
            "よくある質問や案内の文章の整理",
            "不具合の聞き取りと、技術者への引き継ぎ",
            "新しく来た方への使い方の案内",
        ], "丁寧な文章が書ける方。ASHIKA Network や Discord を使ったことがある方は、すぐに力になれます。"),
    ],
    "roles_want": "こんな方を歓迎します",
    "perks_t": "参加してくれる方へ",
    "perks": [
        ("server", f"サーバー最大 {JOIN_SERVERS} 台が無料", f"参加している間、ASHIKA Network のサーバーを同時に {JOIN_SERVERS} 台まで、月額料金なしで使えます。プランは活動に合わせてご相談のうえ決めます。"),
        ("mail", "活動用のメールアドレス", "ASHIKA Group としてお客様や外部とやりとりするための、専用のメールアドレスをお渡しします。"),
        ("spark", "本物のサービス運営の経験", "実際にお客様がいるサービスの開発・運用・サポートに関われます。"),
        ("check", "時間は自由・ノルマなし", "学校や仕事の合間で大丈夫です。できるときに、できる分だけ。"),
    ],
    "steps_t": "参加までの流れ",
    "steps": [
        ("応募", "メールか Discord で、下の「応募のしかた」の内容を送ってください。"),
        ("お話し", "Discord で、できることや希望を軽くお聞きします（30 分ほど）。"),
        ("参加", "権限・メールアドレス・特典のサーバーを用意して、活動を始めます。"),
    ],
    "apply_t": "応募のしかた",
    "apply_p": "件名を「お手伝い応募」として、次の内容を送ってください。",
    "apply_items": ["お名前（ハンドルネームでも大丈夫です）", "希望する役割（技術者・お客様対応・どちらでも）", "できること・これまでの経験（作ったものがあれば URL も）", "連絡のつく Discord のユーザー名", "18 歳未満の方は、年齢と保護者の方の同意"],
    "apply_mail": "メールで応募する",
    "apply_discord": "Discord で相談する",
    "join_faq_t": "よくある質問",
    "join_faq": [
        ("お給料はもらえますか？", "いいえ。お手伝いはボランティアで、雇用や業務委託ではありません。サーバーとメールアドレスは、活動を支えるための特典としてお渡しします。"),
        ("どのくらいの時間、活動すればいいですか？", "決まりはありません。ノルマもありません。続けられるペースで関わってください。"),
        ("経験がなくても大丈夫ですか？", "お客様対応は、丁寧なやりとりができれば経験は問いません。技術者も、学びながら関わりたい方を歓迎します。"),
        ("特典のサーバーはどんなプランですか？", f"同時に {JOIN_SERVERS} 台まで、月額料金なしで使えます。性能やプランは、活動内容に合わせてご相談のうえ決めます。"),
        ("辞めたくなったら？", "いつでも辞められます。辞めたあとのサーバーの扱いは、メンバー規約の第 4 条をご覧ください。"),
    ],
    "disclaimer_t": "免責事項",
    "disclaimer": [
        "お手伝いは、雇用契約や業務委託契約ではありません。報酬はお支払いしません。",
        "特典のサーバーは、稼働やデータの保全を保証するものではありません。大切なデータは、ご自身でもバックアップを取ってください。",
        "活動中に生じた損害について、ASHIKA Group は故意または重大な過失がある場合を除き、責任を負いません。",
        "募集の内容や特典は、予告なく変わったり、終了したりすることがあります。",
    ],
    "terms_link": "メンバー規約を読む",
    "terms_k": "Terms",
    "terms_t": "お手伝いメンバー規約",
    "terms_p": "ASHIKA Group のお手伝いに参加する方との約束です。参加の前にお読みください。",
    "terms_dated": "2026年10月4日 制定",
    "terms": [
        ("目的", ["この規約は、ASHIKA Group（以下「当グループ」）の活動を手伝う方（以下「メンバー」）と当グループとの約束を定めます。", "メンバーとして参加した方は、この規約に同意したものとします。"]),
        ("活動の性質", ["メンバーの活動はボランティアです。当グループとメンバーの間に、雇用・業務委託・請負などの契約は生じません。", "当グループはメンバーに報酬を支払いません。第 4 条・第 5 条の特典は、活動を支えるためのもので、報酬ではありません。", "活動の時間や量に決まりやノルマはありません。"]),
        ("参加の条件", ["参加には、応募と当グループによる確認が必要です。当グループは、理由を示さずに参加をお断りすることがあります。", "18 歳未満の方は、保護者の方の同意を得たうえで応募してください。", "応募の内容に事実と違うことがあった場合、参加を取り消すことがあります。"]),
        ("特典のサーバー", [f"メンバーは参加している間、ASHIKA Network のサーバーを同時に最大 {JOIN_SERVERS} 台まで、月額料金なしで使えます。プランや性能は、活動内容に応じて当グループが決めます。", "特典のサーバーにも、ASHIKA Network の利用規約と利用方針（AUP）が適用されます。", "特典のサーバーを、他人に譲ったり、貸したり、売ったりすることはできません。", "メンバーでなくなったときは、30 日以内に、有料での利用に切り替えるか、データを移してください。期限を過ぎたサーバーは停止し、データを削除します。", "当グループは、特典の内容を変えたり、終了したりすることがあります。その場合は、できるだけ早くメンバーにお知らせします。"]),
        ("専用のメールアドレス", ["当グループは、活動のために専用のメールアドレスをお渡しします。", "このメールアドレスは、当グループの活動にだけ使ってください。個人的なサービスへの登録、営利目的の利用、当グループの名前を使った無断の発信には使えません。", "メールアドレスとそのデータは当グループが管理します。法令に基づく場合やトラブルの調査に必要な場合には、当グループが内容を確認することがあります。", "パスワードは他人に教えず、二段階認証を設定してください。", "メンバーでなくなったときは、メールアドレスを停止します。"]),
        ("秘密と個人情報", ["活動で知ったお客様の情報や、当グループの内部の情報は、外に出したり、活動以外に使ったりしないでください。", "お客様の個人情報は、当グループのプライバシーポリシーに従って扱ってください。", "この条の約束は、メンバーでなくなったあとも続きます。"]),
        ("お客様への対応", ["お客様には、当グループの方針に沿って、丁寧に対応してください。", "返金や補償など、当グループとして約束が必要なことは、自分だけで決めずに運営に引き継いでください。", "当グループが渡す管理画面などの権限は、活動に必要な範囲でだけ使い、他人に共有しないでください。"]),
        ("つくったもの", ["メンバーが活動のためにつくったプログラムや文章の権利は、メンバーに残ります。", "ただし当グループは、それらを当グループのサービスのために、無償で、期限なく使い、変えることができるものとします。", "オープンソースのリポジトリへの貢献は、そのリポジトリのライセンスに従います。"]),
        ("禁止事項", ["法令や公序良俗に反すること", "お客様、ほかのメンバー、第三者に迷惑をかけること", "渡された権限やメールアドレスを、目的の外で使うこと", "当グループの名前を使って、許可なく外部に発信すること", "そのほか、当グループが不適切と判断すること"]),
        ("免責", ["当グループは、メンバーが活動の中で受けた損害について、当グループに故意または重大な過失がある場合を除き、責任を負いません。", "当グループは、特典のサーバーやメールアドレスが止まらないこと、データが失われないことを保証しません。", "メンバーが規約に違反して当グループやお客様に損害を与えた場合、メンバーはその損害について責任を負うことがあります。"]),
        ("終わり", ["メンバーは、いつでも申し出て活動を終えられます。", "メンバーが規約に違反した場合、当グループは知らせたうえで、または緊急のときは知らせずに、参加を終えることがあります。", "参加が終わったときは、権限とメールアドレスを停止します。特典のサーバーは第 4 条に従います。"]),
        ("規約の変更", ["当グループは、この規約を変えることがあります。大切な変更は、事前にメンバーにお知らせします。", "変更後も活動を続けたメンバーは、変更に同意したものとします。"]),
        ("準拠法と裁判所", ["この規約は日本の法律に従います。", "この規約に関する争いは、大阪地方裁判所を第一審の専属的合意管轄裁判所とします。"]),
    ],
    "terms_article": "第 {n} 条",
    "terms_back": "お手伝い募集に戻る",
})

T["en-us"].update({
    "join_k": "Join us",
    "join_t": "Join us",
    "join_p": "ASHIKA Group is run by a small team. We are looking for people to help keep our services running.",
    "join_open": "Open",
    "join_home_t": "Build it with us.",
    "join_home_p": f"We are looking for engineers and support helpers. While you help, you can use up to {JOIN_SERVERS} ASHIKA Network servers for free.",
    "roles_t": "Roles",
    "roles": [
        ("engineer", "Engineer", "技術者", "Build and look after the systems behind our services.", [
            "Maintain and improve ASHIKA Network's servers and customer panel",
            "Develop Storia, our Minecraft server software",
            "Improve our websites",
            "Help investigate and recover from outages",
        ], "Some experience with Linux, Docker, TypeScript, Python or Java. Something you built and ran yourself, however small, is a big plus."),
        ("support", "Support", "お客様対応", "Help the people who use our services, right where they need it.", [
            "Answer Discord tickets and enquiries",
            "Keep FAQs and guides clear and up to date",
            "Find out what went wrong and hand it over to an engineer",
            "Show newcomers how things work",
        ], "You write clearly and politely. If you have used ASHIKA Network or Discord, you can help right away."),
    ],
    "roles_want": "Who we are looking for",
    "perks_t": "What you get",
    "perks": [
        ("server", f"Up to {JOIN_SERVERS} servers for free", f"While you help, you can run up to {JOIN_SERVERS} ASHIKA Network servers at a time without a monthly fee. We agree on the plans together, based on what you work on."),
        ("mail", "Your own work email address", "An email address for talking with customers and others on behalf of ASHIKA Group."),
        ("spark", "Real-world experience", "Work on the development, operation and support of services with real customers."),
        ("check", "Your own pace, no quotas", "Fit it around school or work. Help when you can, as much as you can."),
    ],
    "steps_t": "How it works",
    "steps": [
        ("Apply", "Send us the details under “How to apply” by email or on Discord."),
        ("Chat", "A short call on Discord about what you can do and what you would like to do (about 30 minutes)."),
        ("Start", "We set up your access, email address and servers, and you get started."),
    ],
    "apply_t": "How to apply",
    "apply_p": "Use the subject “Joining ASHIKA Group” and include:",
    "apply_items": ["Your name (a nickname is fine)", "The role you would like (engineer, support, or either)", "What you can do and your experience (links to things you made, if any)", "Your Discord username", "If you are under 18: your age and your parent's or guardian's consent"],
    "apply_mail": "Apply by email",
    "apply_discord": "Ask on Discord",
    "join_faq_t": "FAQ",
    "join_faq": [
        ("Is this paid?", "No. Helping is volunteer work, not employment or a contract. The servers and email address are perks that support your work."),
        ("How much time do I need to give?", "There is no minimum and no quota. Help at a pace you can keep up."),
        ("Do I need experience?", "Not for support, as long as you communicate politely. For engineering, people who want to learn along the way are welcome too."),
        ("What kind of servers do I get?", f"Up to {JOIN_SERVERS} at a time, with no monthly fee. We agree on the specs and plans based on what you work on."),
        ("What if I want to stop?", "You can stop at any time. What happens to your servers afterwards is in Article 4 of the member terms."),
    ],
    "disclaimer_t": "Disclaimer",
    "disclaimer": [
        "Helping is not employment or a service contract. No payment is made.",
        "The perk servers come with no guarantee of uptime or data retention. Please keep your own backups of anything important.",
        "ASHIKA Group is not liable for any damage that occurs while you help, except in cases of intent or gross negligence on our part.",
        "This call for helpers and its perks may change or end without notice.",
    ],
    "terms_link": "Read the member terms",
    "terms_k": "Terms",
    "terms_t": "Member terms",
    "terms_p": "Our agreement with the people who help ASHIKA Group. Please read it before you join. The Japanese version is the official one.",
    "terms_dated": "Effective October 4, 2026",
    "terms": [
        ("Purpose", ["These terms set out the agreement between ASHIKA Group (“we”) and the people who help with our activities (“members”).", "By joining as a member, you agree to these terms."]),
        ("Nature of the work", ["Members are volunteers. No employment, service or work contract arises between us and members.", "We do not pay members. The perks in Articles 4 and 5 support your work and are not payment.", "There is no required amount of time and no quota."]),
        ("Joining", ["Joining requires an application and our confirmation. We may decline an application without giving a reason.", "If you are under 18, please apply with the consent of a parent or guardian.", "We may cancel a membership if the application contained false information."]),
        ("Perk servers", [f"While you are a member, you may use up to {JOIN_SERVERS} ASHIKA Network servers at a time without a monthly fee. We decide the plans and specs based on your work.", "ASHIKA Network's terms of service and acceptable use policy also apply to perk servers.", "You may not transfer, lend or sell perk servers to anyone.", "When your membership ends, please switch to paid use or move your data within 30 days. After that, the servers are stopped and their data is deleted.", "We may change or end the perks. If we do, we will tell members as early as we can."]),
        ("Work email address", ["We give members an email address for their work.", "Use it only for ASHIKA Group activities: not for personal sign-ups, commercial purposes, or speaking in our name without permission.", "We manage the address and its data. We may look at its contents when required by law or to investigate a problem.", "Do not share your password, and turn on two-factor authentication.", "The address is disabled when your membership ends."]),
        ("Confidentiality and personal data", ["Do not disclose customer information or our internal information that you learn through your work, or use it for anything else.", "Handle customers' personal data in line with our privacy policy.", "These obligations continue after your membership ends."]),
        ("Working with customers", ["Treat customers politely and in line with our policies.", "Do not promise refunds, compensation or anything else that needs our approval yourself; hand it over to the team.", "Use any admin access we give you only as far as your work needs it, and never share it."]),
        ("Your work", ["Rights in the code and writing you create for your work stay with you.", "You grant us a free, perpetual right to use and modify them for our services.", "Contributions to open-source repositories follow the license of that repository."]),
        ("Prohibited conduct", ["Breaking the law or public order", "Causing trouble for customers, other members or third parties", "Using the access or email address you were given for other purposes", "Speaking publicly in our name without permission", "Anything else we reasonably consider inappropriate"]),
        ("Disclaimer", ["We are not liable for any damage you suffer while helping, except in cases of intent or gross negligence on our part.", "We do not guarantee that perk servers or email addresses will stay up or that data will not be lost.", "If you breach these terms and cause damage to us or our customers, you may be responsible for that damage."]),
        ("Ending membership", ["You may end your membership at any time by telling us.", "If you breach these terms, we may end your membership after telling you, or without notice in urgent cases.", "When membership ends, your access and email address are disabled. Perk servers follow Article 4."]),
        ("Changes", ["We may change these terms. We will tell members about important changes in advance.", "Members who keep helping after a change agree to the changed terms."]),
        ("Governing law and court", ["These terms are governed by the laws of Japan.", "The Osaka District Court has exclusive jurisdiction in the first instance over any dispute about these terms."]),
    ],
    "terms_article": "Article {n}",
    "terms_back": "Back to Join us",
})


# ---------------------------------------------------------------------------------------------
# Support program: free ASHIKA Network servers for nonprofits and individuals (/supportprogram/, /supportprogram/terms/)
# ---------------------------------------------------------------------------------------------
SUPPORT_NONPROFIT_SERVERS = 20
SUPPORT_PERSONAL_SERVERS = 10
SUPPORT_TERMS_DATE = "2026-10-04"

T["ja-jp"].update({
    "sp_k": "Support program",
    "sp_t": "支援プログラム",
    "sp_p": "お金の心配をせずに、つくり続けられるように。非営利団体と個人の活動を、ASHIKA Network のサーバーで無料で支えます。",
    "sp_home_t": "活動を、サーバーで支えます。",
    "sp_home_p": f"非営利団体は {SUPPORT_NONPROFIT_SERVERS} 台まで、学生やオープンソース開発者などの個人は {SUPPORT_PERSONAL_SERVERS} 台まで、ASHIKA Network のサーバーを無料で使えます。",
    "sp_programs_t": "2 つのプログラム",
    "sp_unit": "台まで無料",
    "sp_more": "それ以上が必要なときは、ご相談ください。",
    "sp_programs": [
        ("nonprofit", "非営利団体向け", "For nonprofits", SUPPORT_NONPROFIT_SERVERS,
         "営利を目的としない団体の活動を支えます。",
         ["NPO 法人、一般社団法人・一般財団法人（非営利型）、公益法人", "学校の部活動・サークル・研究室", "地域の団体やボランティア団体", "法人格のない非営利の団体やコミュニティも、活動内容を見てご相談に応じます"],
         ["団体の名前と、活動内容がわかるもの（ウェブサイト、SNS、資料など）", "代表者または担当者のお名前と連絡先", "サーバーを何に使うか、何台ほど必要か"]),
        ("personal", "個人向け", "For individuals", SUPPORT_PERSONAL_SERVERS,
         "お金の心配なく、学んだり、つくったり、場を運営したりできるように。",
         ["学生（中学生・高校生・大学生・専門学校生など）", "オープンソースの開発者", "Discord や Minecraft などのコミュニティを、無償で運営している方", "経済的に厳しい方（事情をお聞きして、個別に判断します）"],
         ["お名前（ハンドルネームでも大丈夫です）と連絡先", "どれにあてはまるか、それがわかるもの（学生証、公開しているリポジトリ、運営しているコミュニティなど）", "サーバーを何に使うか、何台ほど必要か", "18 歳未満の方は、保護者の方の同意"]),
    ],
    "sp_who": "対象",
    "sp_need": "申請に書いてほしいこと",
    "sp_hardship_note": "経済的な事情についての証明書類は必要ありません。差し支えない範囲で、状況を教えてください。いただいた内容は、審査のためだけに使います。",
    "sp_steps_t": "使い始めるまで",
    "sp_steps": [
        ("申請", "件名を「支援プログラム申請」として、メールか Discord で申請してください。"),
        ("確認", "内容を確認し、必要なら少しお話を聞かせていただきます。結果はご連絡します。"),
        ("利用開始", "お客様パネルのアカウントに、無料のサーバー枠を用意します。"),
    ],
    "sp_apply_mail": "メールで申請する",
    "sp_apply_discord": "Discord で相談する",
    "sp_faq_t": "よくある質問",
    "sp_faq": [
        ("本当に無料ですか？", f"はい。対象と認められた方は、非営利団体は {SUPPORT_NONPROFIT_SERVERS} 台まで、個人は {SUPPORT_PERSONAL_SERVERS} 台まで、月額料金なしで使えます。"),
        ("どんな性能のサーバーが使えますか？", "使いみちをお聞きしたうえで、合うプランをご相談して決めます。"),
        ("期間はありますか？", "1 年ごとに、続けて使うかを確認します。対象のままであれば、更新できます。"),
        ("お金を稼ぐ活動にも使えますか？", "このプログラムのサーバーは、申請いただいた非営利の活動・学習・オープンソース・無償のコミュニティのために使ってください。収益を目的とする使い方には、有料のプランをご利用ください。"),
        ("お手伝いメンバーの特典とは違いますか？", "別の制度です。お手伝いメンバーの特典は、ASHIKA Group の活動を手伝う方向けのものです。"),
        ("審査に通らなかったら？", "理由をお伝えできる範囲でお知らせします。状況が変わったら、もう一度申請できます。"),
    ],
    "sp_notes_t": "ご注意",
    "sp_notes": [
        "対象かどうかは、ASHIKA Group が申請の内容をもとに判断します。お断りすることもあります。",
        "サーバーには、ASHIKA Network の利用規約と利用方針（AUP）が適用されます。",
        "無料のサーバーは、稼働やデータの保全を保証するものではありません。大切なデータはご自身でもバックアップを取ってください。",
        "プログラムの内容は、変わったり終了したりすることがあります。その場合は、できるだけ早くお知らせします。",
    ],
    "sp_terms_link": "支援プログラム規約を読む",
    "spt_k": "Terms",
    "spt_t": "支援プログラム規約",
    "spt_p": "支援プログラムを使う方との約束です。申請の前にお読みください。",
    "spt_dated": "2026年10月4日 制定",
    "spt_terms": [
        ("目的", ["この規約は、ASHIKA Group（以下「当グループ」）が行う支援プログラム（以下「プログラム」）を使う方（以下「利用者」）と当グループとの約束を定めます。", "プログラムを使い始めた方は、この規約に同意したものとします。"]),
        ("内容", [f"非営利団体向けプログラムの利用者は、ASHIKA Network のサーバーを同時に最大 {SUPPORT_NONPROFIT_SERVERS} 台まで、月額料金なしで使えます。", f"個人向けプログラムの利用者は、ASHIKA Network のサーバーを同時に最大 {SUPPORT_PERSONAL_SERVERS} 台まで、月額料金なしで使えます。", "それより多く必要な場合は、当グループと相談のうえ決めます。", "サーバーのプランや性能は、使いみちに応じて当グループが決めます。"]),
        ("対象と審査", ["プログラムの対象は、支援プログラムのページに書いたとおりです。", "対象かどうかは、申請の内容をもとに当グループが判断します。当グループは、理由をすべて示さずにお断りすることがあります。", "18 歳未満の方は、保護者の方の同意を得たうえで申請してください。", "申請の内容に事実と違うことがあった場合、利用を取り消すことがあります。"]),
        ("期間と更新", ["利用できる期間は、使い始めてから 1 年です。", "続けて使いたい場合は、期間の終わりまでに当グループの確認を受けてください。対象のままであれば更新できます。"]),
        ("使いみち", ["サーバーは、申請した活動（非営利の活動、学習、オープンソースの開発、無償のコミュニティの運営など）のために使ってください。", "収益を主な目的とする使い方はできません。その場合は、有料のプランをご利用ください。", "サーバーを他人に譲ったり、貸したり、売ったりすることはできません。", "ASHIKA Network の利用規約と利用方針（AUP）も適用されます。"]),
        ("個人情報", ["申請でいただいた情報は、審査、連絡、プログラムの運営のためだけに使い、ASHIKA Network のプライバシーポリシーに従って扱います。", "経済的な事情など、審査のために伺った内容を、本人の同意なく外に出すことはありません。"]),
        ("利用の終わり", ["利用者は、いつでもプログラムをやめられます。", "対象でなくなったとき、規約に違反したとき、または期間が終わって更新しなかったときは、プログラムの利用が終わります。", "利用が終わったときは、30 日以内に、有料での利用に切り替えるか、データを移してください。期限を過ぎたサーバーは停止し、データを削除します。"]),
        ("免責", ["当グループは、プログラムのサーバーが止まらないこと、データが失われないことを保証しません。", "当グループは、プログラムの利用によって利用者に生じた損害について、当グループに故意または重大な過失がある場合を除き、責任を負いません。"]),
        ("変更と終了", ["当グループは、プログラムの内容やこの規約を変えたり、プログラムを終えたりすることがあります。", "大切な変更や終了は、できるだけ早く利用者にお知らせします。変更後も使い続けた利用者は、変更に同意したものとします。"]),
        ("準拠法と裁判所", ["この規約は日本の法律に従います。", "この規約に関する争いは、大阪地方裁判所を第一審の専属的合意管轄裁判所とします。"]),
    ],
    "spt_back": "支援プログラムに戻る",
})

T["en-us"].update({
    "sp_k": "Support program",
    "sp_t": "Support program",
    "sp_p": "So you can keep building without worrying about money. We support nonprofits and individuals with free ASHIKA Network servers.",
    "sp_home_t": "Servers for good causes.",
    "sp_home_p": f"Nonprofits can use up to {SUPPORT_NONPROFIT_SERVERS} ASHIKA Network servers for free, and individuals such as students and open-source developers up to {SUPPORT_PERSONAL_SERVERS}.",
    "sp_programs_t": "Two programs",
    "sp_unit": "servers free",
    "sp_more": "Need more? Talk to us.",
    "sp_programs": [
        ("nonprofit", "For nonprofits", "非営利団体向け", SUPPORT_NONPROFIT_SERVERS,
         "Supporting organizations that do not work for profit.",
         ["NPOs, nonprofit general incorporated associations and foundations, public interest corporations", "School clubs, circles and research labs", "Local groups and volunteer organizations", "Unincorporated nonprofit groups and communities are welcome to ask too"],
         ["Your organization's name and something that shows what it does (website, social media, documents)", "The name and contact details of your representative or contact person", "What you will use the servers for, and roughly how many you need"]),
        ("personal", "For individuals", "個人向け", SUPPORT_PERSONAL_SERVERS,
         "So you can learn, build and run your community without worrying about cost.",
         ["Students (middle school, high school, university, vocational school and so on)", "Open-source developers", "People running Discord, Minecraft or other communities for free", "People facing financial hardship (we look at each case individually)"],
         ["Your name (a nickname is fine) and contact details", "Which group you belong to, and something that shows it (student ID, public repositories, the community you run)", "What you will use the servers for, and roughly how many you need", "If you are under 18: your parent's or guardian's consent"]),
    ],
    "sp_who": "Who it is for",
    "sp_need": "What to include in your application",
    "sp_hardship_note": "No documents are needed to show financial hardship. Tell us about your situation as far as you are comfortable. We use it only to review your application.",
    "sp_steps_t": "How to get started",
    "sp_steps": [
        ("Apply", "Send your application by email or on Discord, with the subject “Support program application”."),
        ("Review", "We review it and may ask you a few questions. We will let you know the result."),
        ("Start", "We add free server slots to your customer panel account."),
    ],
    "sp_apply_mail": "Apply by email",
    "sp_apply_discord": "Ask on Discord",
    "sp_faq_t": "FAQ",
    "sp_faq": [
        ("Is it really free?", f"Yes. Once accepted, nonprofits can use up to {SUPPORT_NONPROFIT_SERVERS} servers and individuals up to {SUPPORT_PERSONAL_SERVERS}, with no monthly fee."),
        ("What kind of servers do I get?", "We ask what you will use them for and agree on suitable plans together."),
        ("Is there a time limit?", "We check every year whether you want to continue. If you still qualify, you can renew."),
        ("Can I use them to make money?", "Please use program servers for the nonprofit work, learning, open source or free community you applied with. For uses mainly aimed at income, please use a paid plan."),
        ("Is this the same as the helper perks?", "No, it is a separate program. The helper perks are for people who help with ASHIKA Group's work."),
        ("What if my application is declined?", "We tell you why as far as we can. If your situation changes, you can apply again."),
    ],
    "sp_notes_t": "Please note",
    "sp_notes": [
        "ASHIKA Group decides who qualifies based on the application, and may decline applications.",
        "ASHIKA Network's terms of service and acceptable use policy apply to these servers.",
        "Free servers come with no guarantee of uptime or data retention. Please keep your own backups of anything important.",
        "The program may change or end. If it does, we will tell you as early as we can.",
    ],
    "sp_terms_link": "Read the support program terms",
    "spt_k": "Terms",
    "spt_t": "Support program terms",
    "spt_p": "Our agreement with the people who use the support program. Please read it before you apply. The Japanese version is the official one.",
    "spt_dated": "Effective October 4, 2026",
    "spt_terms": [
        ("Purpose", ["These terms set out the agreement between ASHIKA Group (“we”) and the people who use our support program (“the program”, “users”).", "By starting to use the program, you agree to these terms."]),
        ("What the program offers", [f"Users of the nonprofit program may use up to {SUPPORT_NONPROFIT_SERVERS} ASHIKA Network servers at a time without a monthly fee.", f"Users of the individual program may use up to {SUPPORT_PERSONAL_SERVERS} ASHIKA Network servers at a time without a monthly fee.", "If you need more, we decide together.", "We decide the plans and specs based on how the servers will be used."]),
        ("Eligibility and review", ["Who the program is for is described on the support program page.", "We decide whether you qualify based on your application, and may decline without giving every reason.", "If you are under 18, please apply with the consent of a parent or guardian.", "We may cancel your use if your application contained false information."]),
        ("Period and renewal", ["You may use the program for one year from when you start.", "To continue, ask us to confirm before the end of the period. If you still qualify, you can renew."]),
        ("Use", ["Use the servers for the activity you applied with (nonprofit work, learning, open-source development, running a free community and so on).", "The servers may not be used mainly to make money. For that, please use a paid plan.", "You may not transfer, lend or sell the servers to anyone.", "ASHIKA Network's terms of service and acceptable use policy also apply."]),
        ("Personal data", ["We use the information in your application only to review it, contact you and run the program, and handle it under ASHIKA Network's privacy policy.", "We never disclose what you tell us for the review, such as financial circumstances, without your consent."]),
        ("When use ends", ["You may stop using the program at any time.", "Your use ends if you no longer qualify, if you breach these terms, or if the period ends without renewal.", "When your use ends, please switch to paid use or move your data within 30 days. After that, the servers are stopped and their data is deleted."]),
        ("Disclaimer", ["We do not guarantee that program servers will stay up or that data will not be lost.", "We are not liable for any damage caused by using the program, except in cases of intent or gross negligence on our part."]),
        ("Changes and ending the program", ["We may change the program or these terms, or end the program.", "We will tell users about important changes or the end of the program as early as we can. Users who keep using the program after a change agree to it."]),
        ("Governing law and court", ["These terms are governed by the laws of Japan.", "The Osaka District Court has exclusive jurisdiction in the first instance over any dispute about these terms."]),
    ],
    "spt_back": "Back to the support program",
})
