"""Everything the ASHIKA Group site says, in Japanese and English. Edit text here; build.py turns it into pages."""

SERVICES = [
    {
        "key": "ashikanw",
        "name": "ASHIKA Network",
        "url": "https://www.ashikanw.com",
        "host": "ashikanw.com",
        "img": "ashikanw.webp",
        "ja": {
            "kind": "サーバーホスティング",
            "lead": "Discord Bot や Web アプリ、定期実行のスクリプトなど、動かし続けたいプログラムの置き場所を月 30 円から提供しています。",
            "points": [
                "大阪・北摂エリアのデータセンターで運用",
                "1 か月単位の契約で、長い縛りはなし",
                "Python・Node.js・Minecraft などをパネルから数クリックで",
            ],
        },
        "en": {
            "kind": "Server hosting",
            "lead": "A home for programs that must keep running, such as Discord bots, web apps and scheduled scripts, from 30 yen a month.",
            "points": [
                "Run in a data center in northern Osaka",
                "Month-to-month plans, no long contracts",
                "Python, Node.js, Minecraft and more in a few clicks",
            ],
        },
    },
    {
        "key": "storiamc",
        "name": "StoriaMC",
        "url": "https://storiamc.com",
        "host": "storiamc.com",
        "img": "storiamc.webp",
        "ja": {
            "kind": "ソフトウェア（オープンソース）",
            "lead": "大規模な Minecraft サーバーのためのサーバーソフトウェア「Storia」を開発しています。1 つのワールドを複数のサーバーで分担して動かせます。",
            "points": [
                "Storia Cluster：サーバー間を読み込み画面なしで移動",
                "RAM ワールド、Tick Guard、Linear 形式などの独自機能",
                "ソースコードを GitHub で公開",
            ],
        },
        "en": {
            "kind": "Software (open source)",
            "lead": "We build Storia, server software for large Minecraft servers. One world can run on several servers at once.",
            "points": [
                "Storia Cluster: move between servers without a loading screen",
                "RAM world, Tick Guard, the Linear region format and more",
                "Source code on GitHub",
            ],
        },
    },
    {
        "key": "sabalisu",
        "name": "SABALISU",
        "url": "https://minecrafts.jp",
        "host": "minecrafts.jp",
        "img": "sabalisu.webp",
        "ja": {
            "kind": "Minecraft サーバーリスト",
            "lead": "国内の Minecraft サーバーを探せるサーバーリストです。遊ぶ場所を探す人と、仲間を集めたいサーバーをつなぎます。",
            "points": [
                "プレイヤー数と PING を 5 分ごとに実測",
                "経済・サバイバル・PvP などのジャンルで探せる",
                "Microsoft アカウントでログインして投票",
            ],
        },
        "en": {
            "kind": "Minecraft server list",
            "lead": "A list of Minecraft servers in Japan, connecting players looking for a place to play with servers looking for players.",
            "points": [
                "Player counts and ping measured every 5 minutes",
                "Browse by genre: economy, survival, PvP and more",
                "Sign in with a Microsoft account to vote",
            ],
        },
    },
]

T = {
    "ja-jp": {
        "lang": "ja",
        "name": "日本語",
        "title": "ASHIKA Group",
        "desc": "ASHIKA Group は、サーバーホスティングの ASHIKA Network、Minecraft サーバーソフトウェアの StoriaMC、Minecraft サーバーリストの SABALISU を運営しています。",
        "nav": [("services/", "サービス"), ("about/", "ASHIKA Group について"), ("about/#contact", "お問い合わせ")],
        "skip": "本文へ移動",
        "menu": "メニュー",
        "theme": "表示の明るさを切り替える",
        "language": "言語",
        "hero_k": "ASHIKA Group",
        "hero_t": ["情報と世界を", "駆け巡る"],
        "hero_p": "ASHIKA Group は、サーバーとソフトウェアとコミュニティで、インターネットで何かをつくり、続けていく人を支えています。",
        "hero_cta": ("サービスを見る", "services/"),
        "hero_cta2": ("ASHIKA Group について", "about/"),
        "facts": [("3", "運営しているサービス"), ("30円", "サーバーは月額から"), ("OSS", "Storia はオープンソース"), ("大阪", "箕面市を拠点に運営")],
        "biz_k": "Services",
        "biz_t": "サービス",
        "biz_p": "置き場所をつくる、動かす仕組みをつくる、人と人をつなぐ。3 つのサービスを運営しています。",
        "visit": "サイトを見る",
        "more": "詳しく見る",
        "msg_k": "Message",
        "msg_t": "代表者挨拶",
        "msg_short": "動かし続けたいものを、動かし続けられる場所を。小さなチームでも、大きな仕組みに負けないサービスをつくります。",
        "msg_body": [
            "ASHIKA Group のウェブサイトをご覧いただき、ありがとうございます。",
            "「情報と世界を駆け巡る」。それが私たちの合言葉です。情報が自由に世界を行き交い、人と人がつながり続けるための仕組みを、私たちはつくっています。Discord の Bot、学校の課題でつくった Web アプリ、仲間と遊ぶための Minecraft サーバー。インターネットには、誰かが手間と時間をかけてつくり、動かし続けているものがたくさんあります。けれど、それを置いておく場所の費用や、規模が大きくなったときの仕組みの限界が、続けることを難しくしてしまう場面を、私自身も何度も見てきました。",
            "ASHIKA Network は、月 30 円から使えるサーバーで、その「置き場所」の壁を低くするために始めました。StoriaMC では、たくさんの人が集まる Minecraft サーバーでも快適に動き続けるソフトウェアを、ソースコードを公開しながら開発しています。SABALISU は、遊ぶ場所を探している人と、仲間を待っているサーバーをつなぐ場所です。",
            "どのサービスも、まだ小さなチームで運営しています。だからこそ、利用してくださる方の声に近いところで、一つひとつの改善を積み重ねていきます。これからも ASHIKA Group をよろしくお願いいたします。",
        ],
        "msg_sign": ("ASHIKA Group 代表", "赤枝 遼佳"),
        "co_k": "About",
        "co_t": "ASHIKA Group について",
        "profile_t": "組織概要",
        "profile": [
            ("名称", "ASHIKA Group（アシカグループ）"),
            ("代表", "代表　赤枝 遼佳（あかし はるか）"),
            ("所在地", "大阪府箕面市<br><small>詳しい住所は、ご請求をいただいた場合にお知らせします。</small>"),
            ("活動内容", "サーバーホスティング（ASHIKA Network）<br>ソフトウェア開発（StoriaMC）<br>Web サービス（SABALISU）"),
            ("お問い合わせ", "support[a]ashikanw.com<br><small>[a] を @ に置き換えてお送りください。</small>"),
        ],
        "org_t": "組織図",
        "org_p": "代表のもとで、3 つのサービスを運営しています。",
        "org_top": ("代表", "赤枝 遼佳"),
        "org_units": [("サーバーホスティング", "ASHIKA Network"), ("ソフトウェア開発", "StoriaMC"), ("Web サービス", "SABALISU")],
        "loc_t": "拠点",
        "loc": [("本拠地", "大阪府箕面市", "ASHIKA Group の運営拠点です。"), ("サーバー設備", "大阪府・北摂エリア", "ASHIKA Network をはじめ、各サービスのサーバーを運用しています。")],
        "contact_t": "お問い合わせ",
        "contact_p": "サービスについてのご質問は、各サービスのサポート窓口が早くお答えできます。それ以外のお問い合わせは、メールでお送りください。",
        "contact_mail": "メールで問い合わせる",
        "contact_rows": [("ASHIKA Network のご利用について", "https://link.ashikanw.com/discord", "Discord のサポート"), ("StoriaMC について", "https://github.com/AKSHRK-Dev/Storia/issues", "GitHub の Issue"), ("SABALISU について", "https://minecrafts.jp", "サイト内のお問い合わせ先")],
        "biz_page_p": "ASHIKA Group が運営しているサービスです。",
        "footer_tag": "情報と世界を駆け巡る",
        "footer_services": "サービス",
        "footer_group": "ASHIKA Group",
        "rights": "© {y} ASHIKA Group",
        "not_found": ("ページが見つかりません", "URL が間違っているか、ページが移動しました。", "トップページへ"),
    },
    "en-us": {
        "lang": "en",
        "name": "English",
        "title": "ASHIKA Group",
        "desc": "ASHIKA Group runs ASHIKA Network (server hosting), StoriaMC (Minecraft server software) and SABALISU (a Minecraft server list).",
        "nav": [("services/", "Services"), ("about/", "About us"), ("about/#contact", "Contact")],
        "skip": "Skip to content",
        "menu": "Menu",
        "theme": "Switch light and dark",
        "language": "Language",
        "hero_k": "ASHIKA Group",
        "hero_t": ["Across information,", "around the world."],
        "hero_p": "ASHIKA Group supports people who build things on the internet and keep them going, with servers, software and community.",
        "hero_cta": ("Our services", "services/"),
        "hero_cta2": ("About us", "about/"),
        "facts": [("3", "services we run"), ("¥30", "servers from, per month"), ("OSS", "Storia is open source"), ("Osaka", "based in Minoh")],
        "biz_k": "Services",
        "biz_t": "Our services",
        "biz_p": "A place to run things, the software to run them, and a way to find each other: three services.",
        "visit": "Visit site",
        "more": "Learn more",
        "msg_k": "Message",
        "msg_t": "A message from our representative",
        "msg_short": "A place where the things you want to keep running can keep running. A small team building services that hold their own against big systems.",
        "msg_body": [
            "Thank you for visiting ASHIKA Group.",
            "Across information, around the world: that is our motto. We build what lets information travel freely and keeps people connected. A Discord bot, a web app from a school project, a Minecraft server for friends: the internet is full of things that someone built with their own time and keeps running. Yet I have seen many times how the cost of a place to run them, or the limits of the setup once they grow, makes it hard to keep going.",
            "ASHIKA Network started to lower that first barrier, with servers from 30 yen a month. With StoriaMC we build open-source software that keeps busy Minecraft servers running smoothly. SABALISU is where players looking for a place to play meet the servers waiting for them.",
            "All of our services are still run by a small team. That keeps us close to the people who use them, and we will keep improving them one step at a time. Thank you for your continued support of ASHIKA Group.",
        ],
        "msg_sign": ("Representative, ASHIKA Group", "Haruka Akashi"),
        "co_k": "About",
        "co_t": "About us",
        "profile_t": "Overview",
        "profile": [
            ("Name", "ASHIKA Group"),
            ("Representative", "Haruka Akashi"),
            ("Location", "Minoh, Osaka, Japan<br><small>The full address is available on request.</small>"),
            ("Activities", "Server hosting (ASHIKA Network)<br>Software development (StoriaMC)<br>Web services (SABALISU)"),
            ("Contact", "support[a]ashikanw.com<br><small>Replace [a] with @.</small>"),
        ],
        "org_t": "Organization",
        "org_p": "Three services under one representative.",
        "org_top": ("Representative", "Haruka Akashi"),
        "org_units": [("Server hosting", "ASHIKA Network"), ("Software", "StoriaMC"), ("Web services", "SABALISU")],
        "loc_t": "Locations",
        "loc": [("Headquarters", "Minoh, Osaka", "Where ASHIKA Group is run from."), ("Servers", "Northern Osaka", "Where ASHIKA Network and our other services run.")],
        "contact_t": "Contact",
        "contact_p": "For questions about a service, its own support is the fastest. For anything else, please send us an email.",
        "contact_mail": "Send an email",
        "contact_rows": [("Using ASHIKA Network", "https://link.ashikanw.com/discord", "Support on Discord"), ("About StoriaMC", "https://github.com/AKSHRK-Dev/Storia/issues", "Issues on GitHub"), ("About SABALISU", "https://minecrafts.jp", "Contact on the site")],
        "biz_page_p": "The services ASHIKA Group runs.",
        "footer_tag": "Across information, around the world.",
        "footer_services": "Services",
        "footer_group": "ASHIKA Group",
        "rights": "© {y} ASHIKA Group",
        "not_found": ("Page not found", "The address may be wrong, or the page has moved.", "Back to the top page"),
    },
}
