"""Everything the ASHIKA Group site says, in Japanese and English. Edit text here; build.py turns it into pages."""

SERVICES = [
    {
        "key": "ashikanw",
        "name": "ASHIKA Network",
        "url": "https://www.ashikanw.com",
        "host": "ashikanw.com",
        "img": "ashikanw.webp",
        "ja": {
            "kind": "サーバーホスティング",
            "lead": "Discord Bot や Web アプリ、定期実行のスクリプトなど、動かし続けたいプログラムの置き場所を月 30 円から提供しています。",
            "points": [
                "大阪・北摂エリアのデータセンターで運用",
                "1 か月単位の契約で、長い縛りはなし",
                "Python・Node.js・Minecraft などをパネルから数クリックで",
            ],
        },
        "en": {
            "kind": "Server hosting",
            "lead": "A home for programs that must keep running, such as Discord bots, web apps and scheduled scripts, from 30 yen a month.",
            "points": [
                "Run in a data center in northern Osaka",
                "Month-to-month plans, no long contracts",
                "Python, Node.js, Minecraft and more in a few clicks",
            ],
        },
    },
    {
        "key": "storiamc",
        "name": "StoriaMC",
        "url": "https://storiamc.com",
        "host": "storiamc.com",
        "img": "storiamc.webp",
        "ja": {
            "kind": "ソフトウェア（オープンソース）",
            "lead": "大規模な Minecraft サーバーのためのサーバーソフトウェア「Storia」を開発しています。1 つのワールドを複数のサーバーで分担して動かせます。",
            "points": [
                "Storia Cluster：サーバー間を読み込み画面なしで移動",
                "RAM ワールド、Tick Guard、Linear 形式などの独自機能",
                "ソースコードを GitHub で公開",
            ],
        },
        "en": {
            "kind": "Software (open source)",
            "lead": "We build Storia, server software for large Minecraft servers. One world can run on several servers at once.",
            "points": [
                "Storia Cluster: move between servers without a loading screen",
                "RAM world, Tick Guard, the Linear region format and more",
                "Source code on GitHub",
            ],
        },
    },
    {
        "key": "sabalisu",
        "name": "SABALISU",
        "url": "https://minecrafts.jp",
        "host": "minecrafts.jp",
        "img": "sabalisu.webp",
        "ja": {
            "kind": "Minecraft サーバーリスト",
            "lead": "国内の Minecraft サーバーを探せるサーバーリストです。遊ぶ場所を探す人と、仲間を集めたいサーバーをつなぎます。",
            "points": [
                "プレイヤー数と PING を 5 分ごとに実測",
                "経済・サバイバル・PvP などのジャンルで探せる",
                "Microsoft アカウントでログインして投票",
            ],
        },
        "en": {
            "kind": "Minecraft server list",
            "lead": "A list of Minecraft servers in Japan, connecting players looking for a place to play with servers looking for players.",
            "points": [
                "Player counts and ping measured every 5 minutes",
                "Browse by genre: economy, survival, PvP and more",
                "Sign in with a Microsoft account to vote",
            ],
        },
    },
]

T = {
    "ja-jp": {
        "lang": "ja",
        "name": "日本語",
        "title": "ASHIKA Group",
        "desc": "ASHIKA Group は、サーバーホスティングの ASHIKA Network、Minecraft サーバーソフトウェアの StoriaMC、Minecraft サーバーリストの SABALISU を運営しています。",
        "nav": [("services/", "サービス"), ("vision/", "理念"), ("history/", "沿革"), ("technology/", "技術・設備"), ("about/", "ASHIKA Group について")],
        "footer_links": [("about/", "ASHIKA Group について"), ("vision/", "理念"), ("history/", "沿革"), ("technology/", "技術・設備"), ("brand/", "ブランド"), ("about/#contact", "お問い合わせ")],
        "skip": "本文へ移動",
        "menu": "メニュー",
        "theme": "表示の明るさを切り替える",
        "language": "言語",
        "hero_k": "ASHIKA Group",
        "hero_t": ["情報と世界を", "駆け巡る"],
        "hero_p": "ASHIKA Group は、サーバーとソフトウェアとコミュニティで、インターネットで何かをつくり、続けていく人を支えています。",
        "hero_cta": ("サービスを見る", "services/"),
        "hero_cta2": ("ASHIKA Group について", "about/"),
        "facts": [("3", "運営しているサービス"), ("30円", "サーバーは月額から"), ("OSS", "Storia はオープンソース"), ("大阪", "箕面市を拠点に運営")],
        "biz_k": "Services",
        "biz_t": "サービス",
        "biz_p": "置き場所をつくる、動かす仕組みをつくる、人と人をつなぐ。3 つのサービスを運営しています。",
        "visit": "サイトを見る",
        "more": "詳しく見る",
        "msg_k": "Message",
        "msg_t": "代表者挨拶",
        "msg_short": "動かし続けたいものを、動かし続けられる場所を。小さなチームでも、大きな仕組みに負けないサービスをつくります。",
        "msg_body": [
            "ASHIKA Group のウェブサイトをご覧いただき、ありがとうございます。",
            "「情報と世界を駆け巡る」。それが私たちの合言葉です。情報が自由に世界を行き交い、人と人がつながり続けるための仕組みを、私たちはつくっています。Discord の Bot、学校の課題でつくった Web アプリ、仲間と遊ぶための Minecraft サーバー。インターネットには、誰かが手間と時間をかけてつくり、動かし続けているものがたくさんあります。けれど、それを置いておく場所の費用や、規模が大きくなったときの仕組みの限界が、続けることを難しくしてしまう場面を、私自身も何度も見てきました。",
            "ASHIKA Network は、月 30 円から使えるサーバーで、その「置き場所」の壁を低くするために始めました。StoriaMC では、たくさんの人が集まる Minecraft サーバーでも快適に動き続けるソフトウェアを、ソースコードを公開しながら開発しています。SABALISU は、遊ぶ場所を探している人と、仲間を待っているサーバーをつなぐ場所です。",
            "どのサービスも、まだ小さなチームで運営しています。だからこそ、利用してくださる方の声に近いところで、一つひとつの改善を積み重ねていきます。これからも ASHIKA Group をよろしくお願いいたします。",
        ],
        "msg_sign": ("ASHIKA Group 代表", "赤枝 遼佳"),
        "co_k": "About",
        "co_t": "ASHIKA Group について",
        "profile_t": "組織概要",
        "profile": [
            ("名称", "ASHIKA Group（アシカグループ）"),
            ("代表", "代表　赤枝 遼佳（あかし はるか）"),
            ("所在地", "大阪府箕面市<br><small>詳しい住所は、ご請求をいただいた場合にお知らせします。</small>"),
            ("活動内容", "サーバーホスティング（ASHIKA Network）<br>ソフトウェア開発（StoriaMC）<br>Web サービス（SABALISU）"),
            ("お問い合わせ", "support[a]ashikanw.com<br><small>[a] を @ に置き換えてお送りください。</small>"),
        ],
        "org_t": "組織図",
        "org_p": "代表のもとで、3 つのサービスを運営しています。",
        "org_top": ("代表", "赤枝 遼佳"),
        "org_units": [("サーバーホスティング", "ASHIKA Network"), ("ソフトウェア開発", "StoriaMC"), ("Web サービス", "SABALISU")],
        "loc_t": "拠点",
        "loc": [("本拠地", "大阪府箕面市", "ASHIKA Group の運営拠点です。"), ("サーバー設備", "大阪府・北摂エリア", "ASHIKA Network をはじめ、各サービスのサーバーを運用しています。")],
        "contact_t": "お問い合わせ",
        "contact_p": "サービスについてのご質問は、各サービスのサポート窓口が早くお答えできます。それ以外のお問い合わせは、メールでお送りください。",
        "contact_mail": "メールで問い合わせる",
        "contact_rows": [("ASHIKA Network のご利用について", "https://link.ashikanw.com/discord", "Discord のサポート"), ("StoriaMC について", "https://github.com/AKSHRK-Dev/Storia/issues", "GitHub の Issue"), ("SABALISU について", "https://minecrafts.jp", "サイト内のお問い合わせ先")],
        "biz_page_p": "ASHIKA Group が運営しているサービスです。",
        "footer_tag": "情報と世界を駆け巡る",
        "footer_services": "サービス",
        "footer_group": "ASHIKA Group",
        "rights": "© {y} ASHIKA Group",
        "not_found": ("ページが見つかりません", "URL が間違っているか、ページが移動しました。", "トップページへ"),
    },
    "en-us": {
        "lang": "en",
        "name": "English",
        "title": "ASHIKA Group",
        "desc": "ASHIKA Group runs ASHIKA Network (server hosting), StoriaMC (Minecraft server software) and SABALISU (a Minecraft server list).",
        "nav": [("services/", "Services"), ("vision/", "Vision"), ("history/", "History"), ("technology/", "Technology"), ("about/", "About us")],
        "footer_links": [("about/", "About us"), ("vision/", "Vision"), ("history/", "History"), ("technology/", "Technology"), ("brand/", "Brand"), ("about/#contact", "Contact")],
        "skip": "Skip to content",
        "menu": "Menu",
        "theme": "Switch light and dark",
        "language": "Language",
        "hero_k": "ASHIKA Group",
        "hero_t": ["Across information,", "around the world."],
        "hero_p": "ASHIKA Group supports people who build things on the internet and keep them going, with servers, software and community.",
        "hero_cta": ("Our services", "services/"),
        "hero_cta2": ("About us", "about/"),
        "facts": [("3", "services we run"), ("¥30", "servers from, per month"), ("OSS", "Storia is open source"), ("Osaka", "based in Minoh")],
        "biz_k": "Services",
        "biz_t": "Our services",
        "biz_p": "A place to run things, the software to run them, and a way to find each other: three services.",
        "visit": "Visit site",
        "more": "Learn more",
        "msg_k": "Message",
        "msg_t": "A message from our representative",
        "msg_short": "A place where the things you want to keep running can keep running. A small team building services that hold their own against big systems.",
        "msg_body": [
            "Thank you for visiting ASHIKA Group.",
            "Across information, around the world: that is our motto. We build what lets information travel freely and keeps people connected. A Discord bot, a web app from a school project, a Minecraft server for friends: the internet is full of things that someone built with their own time and keeps running. Yet I have seen many times how the cost of a place to run them, or the limits of the setup once they grow, makes it hard to keep going.",
            "ASHIKA Network started to lower that first barrier, with servers from 30 yen a month. With StoriaMC we build open-source software that keeps busy Minecraft servers running smoothly. SABALISU is where players looking for a place to play meet the servers waiting for them.",
            "All of our services are still run by a small team. That keeps us close to the people who use them, and we will keep improving them one step at a time. Thank you for your continued support of ASHIKA Group.",
        ],
        "msg_sign": ("Representative, ASHIKA Group", "Haruka Akashi"),
        "co_k": "About",
        "co_t": "About us",
        "profile_t": "Overview",
        "profile": [
            ("Name", "ASHIKA Group"),
            ("Representative", "Haruka Akashi"),
            ("Location", "Minoh, Osaka, Japan<br><small>The full address is available on request.</small>"),
            ("Activities", "Server hosting (ASHIKA Network)<br>Software development (StoriaMC)<br>Web services (SABALISU)"),
            ("Contact", "support[a]ashikanw.com<br><small>Replace [a] with @.</small>"),
        ],
        "org_t": "Organization",
        "org_p": "Three services under one representative.",
        "org_top": ("Representative", "Haruka Akashi"),
        "org_units": [("Server hosting", "ASHIKA Network"), ("Software", "StoriaMC"), ("Web services", "SABALISU")],
        "loc_t": "Locations",
        "loc": [("Headquarters", "Minoh, Osaka", "Where ASHIKA Group is run from."), ("Servers", "Northern Osaka", "Where ASHIKA Network and our other services run.")],
        "contact_t": "Contact",
        "contact_p": "For questions about a service, its own support is the fastest. For anything else, please send us an email.",
        "contact_mail": "Send an email",
        "contact_rows": [("Using ASHIKA Network", "https://link.ashikanw.com/discord", "Support on Discord"), ("About StoriaMC", "https://github.com/AKSHRK-Dev/Storia/issues", "Issues on GitHub"), ("About SABALISU", "https://minecrafts.jp", "Contact on the site")],
        "biz_page_p": "The services ASHIKA Group runs.",
        "footer_tag": "Across information, around the world.",
        "footer_services": "Services",
        "footer_group": "ASHIKA Group",
        "rights": "© {y} ASHIKA Group",
        "not_found": ("Page not found", "The address may be wrong, or the page has moved.", "Back to the top page"),
    },
}


# ---------------------------------------------------------------------------------------------
# History: only dates that can be checked (legal pages, GitHub releases, site launches).
# (date, category, ja title, ja text, en title, en text, future?)
# ---------------------------------------------------------------------------------------------
HISTORY = [
    ("2026-07-21", "network",
     "利用規約などを制定", "ASHIKA Network の利用規約、利用方針（AUP）、プライバシーポリシーを定めました。",
     "Terms of service", "ASHIKA Network's terms of service, acceptable use policy and privacy policy took effect.", False),
    ("2026-09-09", "network",
     "チャージ残高の表示を制定", "お客様パネルのチャージ残高について、資金決済法に基づく表示を定めました。",
     "Prepaid balance notice", "The notice under the Payment Services Act for the prepaid balance in the customer panel.", False),
    ("2026-09-26", "storia",
     "Storia を公開", "大規模な Minecraft サーバーのためのサーバーソフトウェア「Storia」の最初のリリース（26.2）を公開し、公式サイト storiamc.com を開設しました。",
     "Storia released", "The first release of Storia (26.2), server software for large Minecraft servers, and its website storiamc.com.", False),
    ("2026-09-27", "storia",
     "Storia Cluster を搭載", "1 つのワールドを複数のサーバーで分担して動かす Storia Cluster を、Storia 26.2-2 で搭載しました。",
     "Storia Cluster", "Storia 26.2-2 brought Storia Cluster: one world, run by several servers at once.", False),
    ("2026-09-28", "storia",
     "プラグイン API を公開", "Cluster の全ワーカーでデータを共有できるプラグイン API を、Storia 26.2-4 で公開しました。",
     "Plugin API", "Storia 26.2-4 added a plugin API that shares data across every worker of a cluster.", False),
    ("2026-10-03", "storia",
     "Linear 形式と予備の Relay", "Storia 26.2-10 で、ディスクの使用量をおよそ半分にする Linear 形式と、壊れても引き継げる予備の Relay に対応しました。",
     "Linear format and a standby relay", "Storia 26.2-10: the Linear region format, about half the disk space, and a standby relay that takes over if the active one is lost.", False),
    ("2026-10-03", "group",
     "ASHIKA Group のサイトを公開", "3 つのサービスをまとめる、ASHIKA Group のウェブサイトを公開しました。",
     "ASHIKA Group website", "The website of ASHIKA Group, home of our three services, went live.", False),
    ("2026-10-13", "network",
     "VPS の受け付けを開始", "専有の IPv4 アドレスとルート権限が付いた VPS の受け付けを始めます。",
     "VPS orders open", "Orders open for VPS plans with a dedicated IPv4 address and root access.", True),
]

REPOS = [
    ("Storia", "AKSHRK-Dev/Storia", "Storia 本体（Folia をもとにしたサーバー）", "Storia itself (a Folia-based server)"),
    ("StoriaProxy", "AKSHRK-Dev/StoriaProxy", "Velocity をもとにしたプロキシ", "A proxy based on Velocity"),
    ("StoriaSite", "AKSHRK-Dev/StoriaSite", "storiamc.com のソース", "Source of storiamc.com"),
    ("ashika-network-site", "AKSHRK-Dev/ashika-network-site", "ashikanw.com のソース", "Source of ashikanw.com"),
    ("ashika-group-site", "AKSHRK-Dev/ashika-group-site", "このサイトのソース", "Source of this website"),
]

COLORS = [("Navy", "#14497e"), ("Blue", "#1b60a6"), ("Ink", "#0e1a2b"), ("Mist", "#f4f7fb"), ("Sky", "#7fb2ea")]

T["ja-jp"].update({
    "ticker": "情報と世界を駆け巡る",
    "cat": {"network": "ASHIKA Network", "storia": "StoriaMC", "group": "ASHIKA Group"},
    "seal_hint": "アシカをつついてみてください",
    "seal_count": "{n} 回つつきました",
    "konami": "アシカがいっぱい！",
    "copied": "コピーしました",
    "future": "予定",
    "date_fmt": "{y}年{m}月{d}日",
    "month_fmt": "{m}月{d}日",
    # vision
    "vision_k": "Vision",
    "vision_t": "理念",
    "vision_p": "「情報と世界を駆け巡る」にこめたことと、ASHIKA Group が大切にしていることです。",
    "words_t": "この言葉にこめたこと",
    "words": [
        ("情報", "Information", "プログラム、言葉、作品、遊び。インターネットを流れるあらゆるものを、私たちは「情報」と呼んでいます。"),
        ("世界", "World", "画面の向こうにいる人たち、ゲームの中に広がる世界、そして私たちが暮らすこの世界。情報は、いつも誰かの世界とつながっています。"),
        ("駆け巡る", "Racing across", "止まらずに、遠くまで、速く。誰かがつくったものが、それを必要とする人のところへ届き続けること。それを支えるのが私たちの仕事です。"),
    ],
    "values_t": "大切にしていること",
    "values": [
        ("止めない", "動き続けることを、いちばんに考えます。Storia の予備の Relay のように、どこかが壊れても止まらない仕組みを選びます。"),
        ("手の届く価格で", "はじめの一歩をためらわないように。ASHIKA Network のサーバーは、月 30 円から使えます。"),
        ("ひらいてつくる", "Storia も、このサイトも、ソースコードを公開しています。誰でも中身を確かめ、手を加えられます。"),
        ("声の近くで", "小さなチームだからこそ、使ってくださる方の声を、すぐに形にします。"),
    ],
    "map_t": "3 つのサービスと理念",
    "map": {
        "ashikanw": ("情報の置き場所", "Bot や Web アプリが、休まず動き続ける場所をつくります。"),
        "storiamc": ("世界を動かす仕組み", "たくさんの人が集まる Minecraft の世界を、止めずに動かします。"),
        "sabalisu": ("世界への入り口", "遊ぶ場所を探す人と、仲間を待つサーバーをつなぎます。"),
    },
    # history
    "hist_k": "History",
    "hist_t": "沿革",
    "hist_p": "ASHIKA Group のこれまでと、これからの予定です。",
    "hist_home_t": "最近のできごと",
    "hist_all": "沿革をすべて見る",
    # technology
    "tech_k": "Technology",
    "tech_t": "技術・設備",
    "tech_p": "サービスを支えている設備と技術です。",
    "tech_stats": [("5", "", "公開しているリポジトリ"), ("5", "分", "ごとにサーバーを計測"), ("1/2", "", "Linear 形式のディスク使用量"), ("30", "円", "サーバーは月額から")],
    "tech": [
        ("ashikanw", "サーバー設備", [
            ("設置場所", "大阪府・北摂エリアのデータセンター"),
            ("動かせるもの", "Python、Node.js、Minecraft など。パネルから数クリックで用意できます。"),
            ("VPS（10 月 13 日から）", "専有の IPv4 アドレスとルート権限付き。最大 64 GB メモリ、10 コア、500 GB SSD。"),
        ]),
        ("storiamc", "サーバーソフトウェア", [
            ("土台", "Paper から派生したマルチスレッドのサーバー Folia をもとに開発。Java 25、Minecraft 26.2 に対応。"),
            ("Storia Cluster", "1 つのワールドを複数のサーバーで分担。サーバー間の通信は、すべて暗号化（AES-GCM）しています。"),
            ("止まらない仕組み", "予備の Storia Relay が本番の内容をその場で写し続け、壊れても引き継げます。"),
            ("保存", "Linear 形式（Zstandard 圧縮）で、ワールドのディスク使用量をおよそ半分に。"),
        ]),
        ("sabalisu", "Web サービス", [
            ("計測", "登録されたサーバーのプレイヤー数と PING を、5 分ごとに実測しています。"),
            ("ログイン", "Microsoft アカウントでログインして投票できます。"),
        ]),
    ],
    "web_t": "ウェブサイト",
    "web": [
        ("配信", "Cloudflare を通して配信し、通信はすべて HTTPS です。"),
        ("このサイト", "Python で作る静的なサイトです。アクセス解析や、追跡のための Cookie は使っていません。"),
    ],
    "oss_t": "オープンソース",
    "oss_p": "次のリポジトリを GitHub で公開しています。",
    # brand
    "brand_k": "Brand",
    "brand_t": "ブランド",
    "brand_p": "ASHIKA Group のマークと色の使い方です。ASHIKA Group やサービスを紹介するときにお使いください。",
    "mark_t": "マーク",
    "mark_p": "ボールを鼻にのせたアシカのマークです。このサイトのトップページのアシカは、ボールの代わりに地球をのせています。",
    "rules_t": "使うときのお願い",
    "rules": [
        ("余白をとる", "マークのまわりに、ボールの直径くらいの余白を空けてください。"),
        ("形を変えない", "伸ばしたり、傾けたり、影や縁取りを付けたりしないでください。"),
        ("色を変えない", "マークの色はネイビーです。暗い背景では、明るくしたものを使います。"),
    ],
    "colors_t": "色",
    "colors_p": "色をクリックすると、カラーコードをコピーできます。",
    "color_use": {"Navy": "メインの色", "Blue": "リンク・アクセント", "Ink": "文字", "Mist": "背景", "Sky": "暗い背景でのメインの色"},
    "type_t": "文字",
    "type_p": "欧文は Inter、和文は Noto Sans JP を使っています。",
    "dl_t": "ダウンロード",
    "dl": [("mark.png", "マーク（PNG・512 × 339）"), ("og.png", "SNS 用の画像（PNG・1200 × 630）")],
    # 404 game
    "game_t": "ボールを落とさないで！",
    "game_p": "ボールをクリック（タップ）して打ち上げてください。何回続くかな？",
    "game_score": "回",
    "game_best": "ベスト",
    "game_start": "スタート",
    "game_again": "もう一度",
})

T["en-us"].update({
    "ticker": "Across information, around the world",
    "cat": {"network": "ASHIKA Network", "storia": "StoriaMC", "group": "ASHIKA Group"},
    "seal_hint": "Give the seal a poke",
    "seal_count": "Poked {n} times",
    "konami": "Seals everywhere!",
    "copied": "Copied",
    "future": "Planned",
    "date_fmt": "{mon} {d}, {y}",
    "month_fmt": "{mon} {d}",
    "vision_k": "Vision",
    "vision_t": "Vision",
    "vision_p": "What we mean by “across information, around the world,” and what matters to ASHIKA Group.",
    "words_t": "What the words mean",
    "words": [
        ("Information", "情報", "Programs, words, creations, play. Everything that flows through the internet is what we call information."),
        ("World", "世界", "The people on the other side of the screen, the worlds inside games, and the world we live in. Information always connects to someone's world."),
        ("Around", "駆け巡る", "Without stopping, far and fast: what someone made keeps reaching the people who need it. Supporting that is our job."),
    ],
    "values_t": "What matters to us",
    "values": [
        ("Keep running", "Staying up comes first. Like Storia's standby relay, we choose designs that keep going when something breaks."),
        ("Within reach", "The first step should be easy. ASHIKA Network servers start at 30 yen a month."),
        ("Built in the open", "Storia and this website are open source. Anyone can read the code and improve it."),
        ("Close to you", "As a small team, we can turn what users tell us into improvements quickly."),
    ],
    "map_t": "Three services, one vision",
    "map": {
        "ashikanw": ("A home for information", "A place where bots and web apps keep running."),
        "storiamc": ("What keeps worlds running", "Busy Minecraft worlds, kept running without a stop."),
        "sabalisu": ("A door to new worlds", "Connecting players looking for a place to play with servers waiting for them."),
    },
    "hist_k": "History",
    "hist_t": "History",
    "hist_p": "Where ASHIKA Group has been, and what comes next.",
    "hist_home_t": "Recent milestones",
    "hist_all": "See the full history",
    "tech_k": "Technology",
    "tech_t": "Technology",
    "tech_p": "The facilities and technology behind our services.",
    "tech_stats": [("5", "", "open-source repositories"), ("5", " min", "between server checks"), ("1/2", "", "disk space with Linear"), ("30", " yen", "servers from, per month")],
    "tech": [
        ("ashikanw", "Server facilities", [
            ("Location", "A data center in northern Osaka"),
            ("What runs", "Python, Node.js, Minecraft and more, set up in a few clicks in the panel."),
            ("VPS (from October 13)", "A dedicated IPv4 address and root access. Up to 64 GB of memory, 10 cores and a 500 GB SSD."),
        ]),
        ("storiamc", "Server software", [
            ("Foundation", "Built on Folia, the multithreaded fork of Paper. Java 25, Minecraft 26.2."),
            ("Storia Cluster", "One world shared by several servers. All traffic between them is encrypted (AES-GCM)."),
            ("No single point of failure", "A standby Storia Relay keeps a live copy and takes over if the active one is lost."),
            ("Storage", "The Linear region format (Zstandard) uses about half the disk space."),
        ]),
        ("sabalisu", "Web service", [
            ("Measured", "Player counts and ping of listed servers, measured every 5 minutes."),
            ("Sign-in", "Sign in with a Microsoft account to vote."),
        ]),
    ],
    "web_t": "Websites",
    "web": [
        ("Delivery", "Served through Cloudflare, HTTPS only."),
        ("This website", "A static site built with Python. No analytics and no tracking cookies."),
    ],
    "oss_t": "Open source",
    "oss_p": "These repositories are public on GitHub.",
    "brand_k": "Brand",
    "brand_t": "Brand",
    "brand_p": "How to use the ASHIKA Group mark and colors when you write about ASHIKA Group or our services.",
    "mark_t": "The mark",
    "mark_p": "A seal balancing a ball on its nose. On this website's home page, the seal balances the globe instead.",
    "rules_t": "Please",
    "rules": [
        ("Give it room", "Leave space around the mark, about the size of the ball."),
        ("Keep its shape", "Do not stretch, tilt, or add shadows or outlines."),
        ("Keep its color", "The mark is navy. On dark backgrounds, use a lighter version."),
    ],
    "colors_t": "Colors",
    "colors_p": "Click a color to copy its code.",
    "color_use": {"Navy": "Main color", "Blue": "Links and accents", "Ink": "Text", "Mist": "Background", "Sky": "Main color on dark backgrounds"},
    "type_t": "Type",
    "type_p": "Inter for Latin text and Noto Sans JP for Japanese.",
    "dl_t": "Downloads",
    "dl": [("mark.png", "The mark (PNG, 512 × 339)"), ("og.png", "Social image (PNG, 1200 × 630)")],
    "game_t": "Don't drop the ball!",
    "game_p": "Click (or tap) the ball to keep it in the air. How long can you last?",
    "game_score": "hits",
    "game_best": "Best",
    "game_start": "Start",
    "game_again": "Play again",
})
